baseURL = 'https://sardar.dev/'
languageCode = 'en-us'
title = 'Raja Sardar'
theme = 'PaperMod'



copyright = "¬© [Sardar.dev](https://sardar.dev/)"
paginate = 5
# theme = [ "hugo-PaperMod" ]
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = [ "posts" ]

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

  [languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# [[languages.en.menu.main]]
# name = "Archive"
# url = "archives"
# weight = 5

# [[languages.en.menu.main]]
# name = "Search"
# url = "search/"
# weight = 10

[[languages.en.menu.main]]
name = "Posts"
url = "posts/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

# [[languages.en.menu.main]]
# name = "WiKi"
# url = "https://github.com/adityatelange/hugo-PaperMod/wiki/"

# [languages.fr]
# languageName = ":fr:"
# weight = 2
# title = "PaperModL2"

#   [languages.fr.taxonomies]
#   category = "FRcategories"
#   tag = "FRtags"
#   series = "FRseries"

# [[languages.fr.menu.main]]
# name = "Archive"
# url = "archives/"
# weight = 5

# [[languages.fr.menu.main]]
# name = "FRTags"
# url = "frtags"
# weight = 10

# [[languages.fr.menu.main]]
# name = "FRCategories"
# url = "frcategories"
# weight = 10

# [[languages.fr.menu.main]]
# name = "FRSeries"
# url = "frseries"
# weight = 10

# [[languages.fr.menu.main]]
# name = "NullLink"
# url = "#"

#   [languages.fr.params]
#   languageAltTitle = "French"

#     [languages.fr.params.profileMode]
#     enabled = true
#     title = "PaperMod"
#     imageUrl = "https://raw.githubusercontent.com/googlefonts/noto-emoji/master/svg/emoji_u1f9d1_1f3fb_200d_1f4bb.svg"
#     imageTitle = "ProfileMode image"
#     subtitle = "‚òÑÔ∏è Fast | ‚òÅÔ∏è Fluent | üåô Smooth | üì± Responsive"

#       [[languages.fr.params.profileMode.buttons]]
#       name = "Blog"
#       url = "posts"

#       [[languages.fr.params.profileMode.buttons]]
#       name = "Profile Mode"
#       url = "https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode"

# [languages.fa]
# languagedirection = "rtl"
# weight = 3
# title = "PaperMod RTL"

#   [languages.fa.taxonomies]
#   category = "FAcategories"
#   tag = "FAtags"
#   series = "FAseries"

# [[languages.fa.menu.main]]
# name = "FATags"
# url = "fatags"
# weight = 10

# [languages.fa.params.homeInfoParams]
# Title = "Hi there üëã"
# Content = "Welcome to RTL layout"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

# [params]
# env = "production"
# description = "Theme PaperMod - https://github.com/rajasardar"
# author = "Raja Sardar"
# defaultTheme = "auto"
# ShowShareButtons = true
# ShowReadingTime = true
# displayFullLangName = true
# ShowPostNavLinks = true
# ShowBreadCrumbs = true
# ShowCodeCopyButtons = true
# ShowRssButtonInSectionTermList = true
# ShowAllPagesInArchive = true
# ShowPageNums = true
# ShowToc = true
# images = [ "images/raja.png" ]

#   [params.profileMode]
#   enabled = false
#   title = "Raja"
#   imageUrl = "#"
#   imageTitle = "my image"

#     [[params.profileMode.buttons]]
#     name = "Archives"
#     url = "archives"

#     [[params.profileMode.buttons]]
#     name = "Tags"
#     url = "tags"

#   [params.homeInfoParams]
#   Title = "Raja Sardar - Welcome to my space"
#   Content = """
# üëã Welcome to demo page of Hugo's theme PaperMod!
# - **PaperMod**  is designed to be clean and simple but fast and responsive theme with useful feature-set that enhances UX.
# - Feel free to show your support by giving us a star üåü on GitHub and sharing with your friends and social media .
# - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper/tree/4330c8b12aa48bfdecbcad6ad66145f679a430b3).
# """

#   [[params.socialIcons]]
#   name = "github"
#   title = "Github"
#   url = "https://github.com/rajasardar"

#   # [[params.socialIcons]]
#   # name = "Discord"
#   # title = "Join discord community"
#   # url = "https://discord.gg/ahpmTvhVmp"

#   [[params.socialIcons]]
#   name = "X"
#   title = "Find me on X/Twitter"
#   url = "https://x.com/mr_rajasardar"

  # [[params.socialIcons]]
  # name = "KoFi"
  # title = "Buy me a Ko-Fi :)"
  # url = "https://ko-fi.com/adityatelange"

  # [params.editPost]
  # URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  # Text = "Suggest Changes"
  # appendFilePath = true

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
